//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Direct2dCad.Lang.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Direct2dCad.Lang.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Accelerated pan and zoom 的本地化字符串。
        /// </summary>
        public static string AcceleratedViewportInteraction {
            get {
                return ResourceManager.GetString("AcceleratedViewportInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add after 的本地化字符串。
        /// </summary>
        public static string AddAfter {
            get {
                return ResourceManager.GetString("AddAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add grid spacing 的本地化字符串。
        /// </summary>
        public static string AddGridSpacingPreset {
            get {
                return ResourceManager.GetString("AddGridSpacingPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add layer 的本地化字符串。
        /// </summary>
        public static string AddLayer {
            get {
                return ResourceManager.GetString("AddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add layout 的本地化字符串。
        /// </summary>
        public static string AddLayout {
            get {
                return ResourceManager.GetString("AddLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add viewport 的本地化字符串。
        /// </summary>
        public static string AddViewport {
            get {
                return ResourceManager.GetString("AddViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angle 的本地化字符串。
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antialias 的本地化字符串。
        /// </summary>
        public static string Antialias {
            get {
                return ResourceManager.GetString("Antialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antialiasing 的本地化字符串。
        /// </summary>
        public static string Antialiasing {
            get {
                return ResourceManager.GetString("Antialiasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Settings 的本地化字符串。
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow nearby zoom cache fallback 的本地化字符串。
        /// </summary>
        public static string ApproximateScaleFallback {
            get {
                return ResourceManager.GetString("ApproximateScaleFallback", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Arc 的本地化字符串。
        /// </summary>
        public static string Arc {
            get {
                return ResourceManager.GetString("Arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center, Start, Angle Arc 的本地化字符串。
        /// </summary>
        public static string ArcCenterStartAngle {
            get {
                return ResourceManager.GetString("ArcCenterStartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center, Start, End Arc 的本地化字符串。
        /// </summary>
        public static string ArcCenterStartEnd {
            get {
                return ResourceManager.GetString("ArcCenterStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center, Start, Length Arc 的本地化字符串。
        /// </summary>
        public static string ArcCenterStartLength {
            get {
                return ResourceManager.GetString("ArcCenterStartLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue Arc 的本地化字符串。
        /// </summary>
        public static string ArcContinue {
            get {
                return ResourceManager.GetString("ArcContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arc drawing 的本地化字符串。
        /// </summary>
        public static string ArcDrawing {
            get {
                return ResourceManager.GetString("ArcDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start, Center, Angle Arc 的本地化字符串。
        /// </summary>
        public static string ArcStartCenterAngle {
            get {
                return ResourceManager.GetString("ArcStartCenterAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start, Center, End Arc 的本地化字符串。
        /// </summary>
        public static string ArcStartCenterEnd {
            get {
                return ResourceManager.GetString("ArcStartCenterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start, Center, Length Arc 的本地化字符串。
        /// </summary>
        public static string ArcStartCenterLength {
            get {
                return ResourceManager.GetString("ArcStartCenterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start, End, Angle Arc 的本地化字符串。
        /// </summary>
        public static string ArcStartEndAngle {
            get {
                return ResourceManager.GetString("ArcStartEndAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start, End, Direction Arc 的本地化字符串。
        /// </summary>
        public static string ArcStartEndDirection {
            get {
                return ResourceManager.GetString("ArcStartEndDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start, End, Radius Arc 的本地化字符串。
        /// </summary>
        public static string ArcStartEndRadius {
            get {
                return ResourceManager.GetString("ArcStartEndRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3-Point Arc 的本地化字符串。
        /// </summary>
        public static string ArcThreePoint {
            get {
                return ResourceManager.GetString("ArcThreePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axes 的本地化字符串。
        /// </summary>
        public static string Axes {
            get {
                return ResourceManager.GetString("Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axes &amp; Marker 的本地化字符串。
        /// </summary>
        public static string AxesAndMarker {
            get {
                return ResourceManager.GetString("AxesAndMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base point 的本地化字符串。
        /// </summary>
        public static string BasePoint {
            get {
                return ResourceManager.GetString("BasePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block definition 的本地化字符串。
        /// </summary>
        public static string BlockDefinition {
            get {
                return ResourceManager.GetString("BlockDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block editing 的本地化字符串。
        /// </summary>
        public static string BlockEditing {
            get {
                return ResourceManager.GetString("BlockEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A block with this name already exists. 的本地化字符串。
        /// </summary>
        public static string BlockNameAlreadyExists {
            get {
                return ResourceManager.GetString("BlockNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block reference 的本地化字符串。
        /// </summary>
        public static string BlockReference {
            get {
                return ResourceManager.GetString("BlockReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blocks 的本地化字符串。
        /// </summary>
        public static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bounds 的本地化字符串。
        /// </summary>
        public static string Bounds {
            get {
                return ResourceManager.GetString("Bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Box Fallback 的本地化字符串。
        /// </summary>
        public static string BoxFallback {
            get {
                return ResourceManager.GetString("BoxFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By block 的本地化字符串。
        /// </summary>
        public static string ByBlock {
            get {
                return ResourceManager.GetString("ByBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By layer 的本地化字符串。
        /// </summary>
        public static string ByLayer {
            get {
                return ResourceManager.GetString("ByLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center X 的本地化字符串。
        /// </summary>
        public static string CenterX {
            get {
                return ResourceManager.GetString("CenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Y 的本地化字符串。
        /// </summary>
        public static string CenterY {
            get {
                return ResourceManager.GetString("CenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circle 的本地化字符串。
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center, Diameter Circle 的本地化字符串。
        /// </summary>
        public static string CircleCenterDiameter {
            get {
                return ResourceManager.GetString("CircleCenterDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center, Radius Circle 的本地化字符串。
        /// </summary>
        public static string CircleCenterRadius {
            get {
                return ResourceManager.GetString("CircleCenterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circle drawing 的本地化字符串。
        /// </summary>
        public static string CircleDrawing {
            get {
                return ResourceManager.GetString("CircleDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3-Point Circle 的本地化字符串。
        /// </summary>
        public static string CircleThreePoint {
            get {
                return ResourceManager.GetString("CircleThreePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2-Point Circle 的本地化字符串。
        /// </summary>
        public static string CircleTwoPoint {
            get {
                return ResourceManager.GetString("CircleTwoPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string ColorPickerAdvanced {
            get {
                return ResourceManager.GetString("ColorPickerAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available Colors 的本地化字符串。
        /// </summary>
        public static string ColorPickerAvailableColors {
            get {
                return ResourceManager.GetString("ColorPickerAvailableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Palettes 的本地化字符串。
        /// </summary>
        public static string ColorPickerPalettes {
            get {
                return ResourceManager.GetString("ColorPickerPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Colors 的本地化字符串。
        /// </summary>
        public static string ColorPickerRecentColors {
            get {
                return ResourceManager.GetString("ColorPickerRecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Colors 的本地化字符串。
        /// </summary>
        public static string ColorPickerStandardColors {
            get {
                return ResourceManager.GetString("ColorPickerStandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color source 的本地化字符串。
        /// </summary>
        public static string ColorSource {
            get {
                return ResourceManager.GetString("ColorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common properties 的本地化字符串。
        /// </summary>
        public static string CommonProperties {
            get {
                return ResourceManager.GetString("CommonProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit the application? 的本地化字符串。
        /// </summary>
        public static string ConfirmExitMessage {
            get {
                return ResourceManager.GetString("ConfirmExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Confirmation 的本地化字符串。
        /// </summary>
        public static string ConfirmExitTitle {
            get {
                return ResourceManager.GetString("ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content type 的本地化字符串。
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coordinates and size 的本地化字符串。
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corner X 的本地化字符串。
        /// </summary>
        public static string CornerX {
            get {
                return ResourceManager.GetString("CornerX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corner Y 的本地化字符串。
        /// </summary>
        public static string CornerY {
            get {
                return ResourceManager.GetString("CornerY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Counter clockwise 的本地化字符串。
        /// </summary>
        public static string CounterClockwise {
            get {
                return ResourceManager.GetString("CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create block 的本地化字符串。
        /// </summary>
        public static string CreateBlock {
            get {
                return ResourceManager.GetString("CreateBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a valid base point. 的本地化字符串。
        /// </summary>
        public static string CreateBlockBasePointInvalid {
            get {
                return ResourceManager.GetString("CreateBlockBasePointInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a block name. 的本地化字符串。
        /// </summary>
        public static string CreateBlockNameRequired {
            get {
                return ResourceManager.GetString("CreateBlockNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create and adjust a layout viewport 的本地化字符串。
        /// </summary>
        public static string CreateViewportMode {
            get {
                return ResourceManager.GetString("CreateViewportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cross 的本地化字符串。
        /// </summary>
        public static string Cross {
            get {
                return ResourceManager.GetString("Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark theme 的本地化字符串。
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dash 的本地化字符串。
        /// </summary>
        public static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dash cap 的本地化字符串。
        /// </summary>
        public static string DashCap {
            get {
                return ResourceManager.GetString("DashCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dash Dot 的本地化字符串。
        /// </summary>
        public static string DashDot {
            get {
                return ResourceManager.GetString("DashDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dash style 的本地化字符串。
        /// </summary>
        public static string DashStyle {
            get {
                return ResourceManager.GetString("DashStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete block 的本地化字符串。
        /// </summary>
        public static string DeleteBlock {
            get {
                return ResourceManager.GetString("DeleteBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete block &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        public static string DeleteBlockConfirmFormat {
            get {
                return ResourceManager.GetString("DeleteBlockConfirmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete grid spacing 的本地化字符串。
        /// </summary>
        public static string DeleteGridSpacingPreset {
            get {
                return ResourceManager.GetString("DeleteGridSpacingPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete layer 的本地化字符串。
        /// </summary>
        public static string DeleteLayer {
            get {
                return ResourceManager.GetString("DeleteLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete layout 的本地化字符串。
        /// </summary>
        public static string DeleteLayout {
            get {
                return ResourceManager.GetString("DeleteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete viewport 的本地化字符串。
        /// </summary>
        public static string DeleteViewport {
            get {
                return ResourceManager.GetString("DeleteViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diameter 的本地化字符串。
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diameter X 的本地化字符串。
        /// </summary>
        public static string DiameterX {
            get {
                return ResourceManager.GetString("DiameterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diameter Y 的本地化字符串。
        /// </summary>
        public static string DiameterY {
            get {
                return ResourceManager.GetString("DiameterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct2dCad 的本地化字符串。
        /// </summary>
        public static string Direct2dCad {
            get {
                return ResourceManager.GetString("Direct2dCad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document name cannot be empty. 的本地化字符串。
        /// </summary>
        public static string DocumentNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("DocumentNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documents 的本地化字符串。
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document Settings 的本地化字符串。
        /// </summary>
        public static string DocumentSettings {
            get {
                return ResourceManager.GetString("DocumentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter valid finite values. Sizes, spacing, and line widths must be greater than zero. 的本地化字符串。
        /// </summary>
        public static string DocumentSettingsInvalidValues {
            get {
                return ResourceManager.GetString("DocumentSettingsInvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t Save 的本地化字符串。
        /// </summary>
        public static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dot 的本地化字符串。
        /// </summary>
        public static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dots 的本地化字符串。
        /// </summary>
        public static string Dots {
            get {
                return ResourceManager.GetString("Dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw 的本地化字符串。
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw order 的本地化字符串。
        /// </summary>
        public static string DrawOrder {
            get {
                return ResourceManager.GetString("DrawOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit block 的本地化字符串。
        /// </summary>
        public static string EditBlock {
            get {
                return ResourceManager.GetString("EditBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit grid spacing 的本地化字符串。
        /// </summary>
        public static string EditGridSpacingPreset {
            get {
                return ResourceManager.GetString("EditGridSpacingPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ellipse 的本地化字符串。
        /// </summary>
        public static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elliptical Arc 的本地化字符串。
        /// </summary>
        public static string EllipseArc {
            get {
                return ResourceManager.GetString("EllipseArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis, End Ellipse 的本地化字符串。
        /// </summary>
        public static string EllipseAxisEnd {
            get {
                return ResourceManager.GetString("EllipseAxisEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Ellipse 的本地化字符串。
        /// </summary>
        public static string EllipseCenter {
            get {
                return ResourceManager.GetString("EllipseCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ellipse drawing 的本地化字符串。
        /// </summary>
        public static string EllipseDrawing {
            get {
                return ResourceManager.GetString("EllipseDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End cap 的本地化字符串。
        /// </summary>
        public static string EndCap {
            get {
                return ResourceManager.GetString("EndCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End X 的本地化字符串。
        /// </summary>
        public static string EndX {
            get {
                return ResourceManager.GetString("EndX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Y 的本地化字符串。
        /// </summary>
        public static string EndY {
            get {
                return ResourceManager.GetString("EndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entities 的本地化字符串。
        /// </summary>
        public static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity Search 的本地化字符串。
        /// </summary>
        public static string EntitySearch {
            get {
                return ResourceManager.GetString("EntitySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All layers 的本地化字符串。
        /// </summary>
        public static string EntitySearchAllLayers {
            get {
                return ResourceManager.GetString("EntitySearchAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All types 的本地化字符串。
        /// </summary>
        public static string EntitySearchAllTypes {
            get {
                return ResourceManager.GetString("EntitySearchAllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current space 的本地化字符串。
        /// </summary>
        public static string EntitySearchCurrentSpace {
            get {
                return ResourceManager.GetString("EntitySearchCurrentSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entire document 的本地化字符串。
        /// </summary>
        public static string EntitySearchEntireDocument {
            get {
                return ResourceManager.GetString("EntitySearchEntireDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity name, ID, layer, or type 的本地化字符串。
        /// </summary>
        public static string EntitySearchHint {
            get {
                return ResourceManager.GetString("EntitySearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer 的本地化字符串。
        /// </summary>
        public static string EntitySearchLayerHint {
            get {
                return ResourceManager.GetString("EntitySearchLayerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No document 的本地化字符串。
        /// </summary>
        public static string EntitySearchNoDocument {
            get {
                return ResourceManager.GetString("EntitySearchNoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} entities 的本地化字符串。
        /// </summary>
        public static string EntitySearchResultCountFormat {
            get {
                return ResourceManager.GetString("EntitySearchResultCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scope 的本地化字符串。
        /// </summary>
        public static string EntitySearchScope {
            get {
                return ResourceManager.GetString("EntitySearchScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string EntitySearchTypeHint {
            get {
                return ResourceManager.GetString("EntitySearchTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity 的本地化字符串。
        /// </summary>
        public static string EntitySettings {
            get {
                return ResourceManager.GetString("EntitySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit block editor 的本地化字符串。
        /// </summary>
        public static string ExitBlockEditor {
            get {
                return ResourceManager.GetString("ExitBlockEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explicit 的本地化字符串。
        /// </summary>
        public static string Explicit {
            get {
                return ResourceManager.GetString("Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill 的本地化字符串。
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill color 的本地化字符串。
        /// </summary>
        public static string FillColor {
            get {
                return ResourceManager.GetString("FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANSI31 的本地化字符串。
        /// </summary>
        public static string FillHatchAnsi31 {
            get {
                return ResourceManager.GetString("FillHatchAnsi31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brick hatch 的本地化字符串。
        /// </summary>
        public static string FillHatchBrick {
            get {
                return ResourceManager.GetString("FillHatchBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cross 45 hatch 的本地化字符串。
        /// </summary>
        public static string FillHatchCross45 {
            get {
                return ResourceManager.GetString("FillHatchCross45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashed hatch 的本地化字符串。
        /// </summary>
        public static string FillHatchDashed {
            get {
                return ResourceManager.GetString("FillHatchDashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dotted hatch 的本地化字符串。
        /// </summary>
        public static string FillHatchDotted {
            get {
                return ResourceManager.GetString("FillHatchDotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid hatch 的本地化字符串。
        /// </summary>
        public static string FillHatchGrid {
            get {
                return ResourceManager.GetString("FillHatchGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal hatch 的本地化字符串。
        /// </summary>
        public static string FillHatchHorizontal {
            get {
                return ResourceManager.GetString("FillHatchHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical hatch 的本地化字符串。
        /// </summary>
        public static string FillHatchVertical {
            get {
                return ResourceManager.GetString("FillHatchVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No fill 的本地化字符串。
        /// </summary>
        public static string FillNoFill {
            get {
                return ResourceManager.GetString("FillNoFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid fill 的本地化字符串。
        /// </summary>
        public static string FillSolid {
            get {
                return ResourceManager.GetString("FillSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        public static string Fit {
            get {
                return ResourceManager.GetString("Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit points 的本地化字符串。
        /// </summary>
        public static string FitPoints {
            get {
                return ResourceManager.GetString("FitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frozen 的本地化字符串。
        /// </summary>
        public static string Frozen {
            get {
                return ResourceManager.GetString("Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geometry 的本地化字符串。
        /// </summary>
        public static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid 的本地化字符串。
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid &amp; Snapping 的本地化字符串。
        /// </summary>
        public static string GridAndSnapping {
            get {
                return ResourceManager.GetString("GridAndSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid appearance 的本地化字符串。
        /// </summary>
        public static string GridAppearance {
            get {
                return ResourceManager.GetString("GridAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid density 的本地化字符串。
        /// </summary>
        public static string GridDensity {
            get {
                return ResourceManager.GetString("GridDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Density preset (major / minor) 的本地化字符串。
        /// </summary>
        public static string GridDensityPreset {
            get {
                return ResourceManager.GetString("GridDensityPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid spacing options 的本地化字符串。
        /// </summary>
        public static string GridSpacingOptions {
            get {
                return ResourceManager.GetString("GridSpacingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A grid spacing with this name already exists. 的本地化字符串。
        /// </summary>
        public static string GridSpacingPresetNameExists {
            get {
                return ResourceManager.GetString("GridSpacingPresetNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spacing must be between 0.001 mm and 100000 mm. 的本地化字符串。
        /// </summary>
        public static string GridSpacingPresetRangeError {
            get {
                return ResourceManager.GetString("GridSpacingPresetRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid spacing selection 的本地化字符串。
        /// </summary>
        public static string GridSpacingSelection {
            get {
                return ResourceManager.GetString("GridSpacingSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid type 的本地化字符串。
        /// </summary>
        public static string GridType {
            get {
                return ResourceManager.GetString("GridType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grip 的本地化字符串。
        /// </summary>
        public static string Grip {
            get {
                return ResourceManager.GetString("Grip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grip preview 的本地化字符串。
        /// </summary>
        public static string GripPreview {
            get {
                return ResourceManager.GetString("GripPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infinite Cross 的本地化字符串。
        /// </summary>
        public static string InfiniteCross {
            get {
                return ResourceManager.GetString("InfiniteCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert block 的本地化字符串。
        /// </summary>
        public static string InsertBlock {
            get {
                return ResourceManager.GetString("InsertBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Image 的本地化字符串。
        /// </summary>
        public static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interaction 的本地化字符串。
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inverted 的本地化字符串。
        /// </summary>
        public static string Inverted {
            get {
                return ResourceManager.GetString("Inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete layer &apos;{0}&apos;? All entities on this layer will be deleted. 的本地化字符串。
        /// </summary>
        public static string LayerDeleteConfirmMessageFormat {
            get {
                return ResourceManager.GetString("LayerDeleteConfirmMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LayerDeleteConfirmTitle 的本地化字符串。
        /// </summary>
        public static string LayerDeleteConfirmTitle {
            get {
                return ResourceManager.GetString("LayerDeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer &quot;{0}&quot; is frozen. 的本地化字符串。
        /// </summary>
        public static string LayerFrozenMessageFormat {
            get {
                return ResourceManager.GetString("LayerFrozenMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer &quot;{0}&quot; is locked. 的本地化字符串。
        /// </summary>
        public static string LayerLockedMessageFormat {
            get {
                return ResourceManager.GetString("LayerLockedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer name already exists. 的本地化字符串。
        /// </summary>
        public static string LayerNameAlreadyExists {
            get {
                return ResourceManager.GetString("LayerNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layers 的本地化字符串。
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout name cannot be empty. 的本地化字符串。
        /// </summary>
        public static string LayoutNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("LayoutNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout settings 的本地化字符串。
        /// </summary>
        public static string LayoutSettings {
            get {
                return ResourceManager.GetString("LayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout viewport 的本地化字符串。
        /// </summary>
        public static string LayoutViewportMode {
            get {
                return ResourceManager.GetString("LayoutViewportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level of detail optimization 的本地化字符串。
        /// </summary>
        public static string LevelOfDetailOptimization {
            get {
                return ResourceManager.GetString("LevelOfDetailOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line drawing 的本地化字符串。
        /// </summary>
        public static string LineDrawing {
            get {
                return ResourceManager.GetString("LineDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line join 的本地化字符串。
        /// </summary>
        public static string LineJoin {
            get {
                return ResourceManager.GetString("LineJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lines 的本地化字符串。
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line weight 的本地化字符串。
        /// </summary>
        public static string LineWeight {
            get {
                return ResourceManager.GetString("LineWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link X and Y 的本地化字符串。
        /// </summary>
        public static string LinkGridAxes {
            get {
                return ResourceManager.GetString("LinkGridAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locked 的本地化字符串。
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major grid color 的本地化字符串。
        /// </summary>
        public static string MajorGridColor {
            get {
                return ResourceManager.GetString("MajorGridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major grid line width 的本地化字符串。
        /// </summary>
        public static string MajorGridLineWidth {
            get {
                return ResourceManager.GetString("MajorGridLineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major grid 的本地化字符串。
        /// </summary>
        public static string MajorGridSpacing {
            get {
                return ResourceManager.GetString("MajorGridSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major spacing X (mm) 的本地化字符串。
        /// </summary>
        public static string MajorGridSpacingXMillimeters {
            get {
                return ResourceManager.GetString("MajorGridSpacingXMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major spacing Y (mm) 的本地化字符串。
        /// </summary>
        public static string MajorGridSpacingYMillimeters {
            get {
                return ResourceManager.GetString("MajorGridSpacingYMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Margin 的本地化字符串。
        /// </summary>
        public static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom margin 的本地化字符串。
        /// </summary>
        public static string MarginBottom {
            get {
                return ResourceManager.GetString("MarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left margin 的本地化字符串。
        /// </summary>
        public static string MarginLeft {
            get {
                return ResourceManager.GetString("MarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right margin 的本地化字符串。
        /// </summary>
        public static string MarginRight {
            get {
                return ResourceManager.GetString("MarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top margin 的本地化字符串。
        /// </summary>
        public static string MarginTop {
            get {
                return ResourceManager.GetString("MarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marker 的本地化字符串。
        /// </summary>
        public static string Marker {
            get {
                return ResourceManager.GetString("Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure 的本地化字符串。
        /// </summary>
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum screen spacing 的本地化字符串。
        /// </summary>
        public static string MinimumScreenSpacing {
            get {
                return ResourceManager.GetString("MinimumScreenSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum world spacing 的本地化字符串。
        /// </summary>
        public static string MinimumWorldSpacing {
            get {
                return ResourceManager.GetString("MinimumWorldSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor grid color 的本地化字符串。
        /// </summary>
        public static string MinorGridColor {
            get {
                return ResourceManager.GetString("MinorGridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor grid line width 的本地化字符串。
        /// </summary>
        public static string MinorGridLineWidth {
            get {
                return ResourceManager.GetString("MinorGridLineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor grid 的本地化字符串。
        /// </summary>
        public static string MinorGridSpacing {
            get {
                return ResourceManager.GetString("MinorGridSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor spacing X (mm) 的本地化字符串。
        /// </summary>
        public static string MinorGridSpacingXMillimeters {
            get {
                return ResourceManager.GetString("MinorGridSpacingXMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minor spacing Y (mm) 的本地化字符串。
        /// </summary>
        public static string MinorGridSpacingYMillimeters {
            get {
                return ResourceManager.GetString("MinorGridSpacingYMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model center X 的本地化字符串。
        /// </summary>
        public static string ModelCenterX {
            get {
                return ResourceManager.GetString("ModelCenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model center Y 的本地化字符串。
        /// </summary>
        public static string ModelCenterY {
            get {
                return ResourceManager.GetString("ModelCenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mono Line 的本地化字符串。
        /// </summary>
        public static string MonoLine {
            get {
                return ResourceManager.GetString("MonoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move down 的本地化字符串。
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move up 的本地化字符串。
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple entity types 的本地化字符串。
        /// </summary>
        public static string MultipleEntityTypes {
            get {
                return ResourceManager.GetString("MultipleEntityTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple values 的本地化字符串。
        /// </summary>
        public static string MultipleValues {
            get {
                return ResourceManager.GetString("MultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object settings 的本地化字符串。
        /// </summary>
        public static string ObjectSettings {
            get {
                return ResourceManager.GetString("ObjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin 的本地化字符串。
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin color 的本地化字符串。
        /// </summary>
        public static string OriginColor {
            get {
                return ResourceManager.GetString("OriginColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin display 的本地化字符串。
        /// </summary>
        public static string OriginDisplayType {
            get {
                return ResourceManager.GetString("OriginDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Line 的本地化字符串。
        /// </summary>
        public static string OriginLine {
            get {
                return ResourceManager.GetString("OriginLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin line pattern 的本地化字符串。
        /// </summary>
        public static string OriginLinePattern {
            get {
                return ResourceManager.GetString("OriginLinePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Marker 的本地化字符串。
        /// </summary>
        public static string OriginMarker {
            get {
                return ResourceManager.GetString("OriginMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin marker type 的本地化字符串。
        /// </summary>
        public static string OriginMarkerType {
            get {
                return ResourceManager.GetString("OriginMarkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin size 的本地化字符串。
        /// </summary>
        public static string OriginSize {
            get {
                return ResourceManager.GetString("OriginSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin line width 的本地化字符串。
        /// </summary>
        public static string OriginStrokeWidth {
            get {
                return ResourceManager.GetString("OriginStrokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan 的本地化字符串。
        /// </summary>
        public static string Pan {
            get {
                return ResourceManager.GetString("Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper 的本地化字符串。
        /// </summary>
        public static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper color 的本地化字符串。
        /// </summary>
        public static string PaperColor {
            get {
                return ResourceManager.GetString("PaperColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper height 的本地化字符串。
        /// </summary>
        public static string PaperHeight {
            get {
                return ResourceManager.GetString("PaperHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper width 的本地化字符串。
        /// </summary>
        public static string PaperWidth {
            get {
                return ResourceManager.GetString("PaperWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Image 的本地化字符串。
        /// </summary>
        public static string PasteImage {
            get {
                return ResourceManager.GetString("PasteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixel height 的本地化字符串。
        /// </summary>
        public static string PixelHeight {
            get {
                return ResourceManager.GetString("PixelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixel width 的本地化字符串。
        /// </summary>
        public static string PixelWidth {
            get {
                return ResourceManager.GetString("PixelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Point count 的本地化字符串。
        /// </summary>
        public static string PointCount {
            get {
                return ResourceManager.GetString("PointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygon 的本地化字符串。
        /// </summary>
        public static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygon drawing 的本地化字符串。
        /// </summary>
        public static string PolygonDrawing {
            get {
                return ResourceManager.GetString("PolygonDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polyline 的本地化字符串。
        /// </summary>
        public static string Polyline {
            get {
                return ResourceManager.GetString("Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polyline drawing 的本地化字符串。
        /// </summary>
        public static string PolylineDrawing {
            get {
                return ResourceManager.GetString("PolylineDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position X 的本地化字符串。
        /// </summary>
        public static string PositionX {
            get {
                return ResourceManager.GetString("PositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position Y 的本地化字符串。
        /// </summary>
        public static string PositionY {
            get {
                return ResourceManager.GetString("PositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary color 的本地化字符串。
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius 的本地化字符串。
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius X 的本地化字符串。
        /// </summary>
        public static string RadiusX {
            get {
                return ResourceManager.GetString("RadiusX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius Y 的本地化字符串。
        /// </summary>
        public static string RadiusY {
            get {
                return ResourceManager.GetString("RadiusY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangle 的本地化字符串。
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangle drawing 的本地化字符串。
        /// </summary>
        public static string RectangleDrawing {
            get {
                return ResourceManager.GetString("RectangleDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 References 的本地化字符串。
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rendering 的本地化字符串。
        /// </summary>
        public static string Rendering {
            get {
                return ResourceManager.GetString("Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation 的本地化字符串。
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation (deg) 的本地化字符串。
        /// </summary>
        public static string RotationDegrees {
            get {
                return ResourceManager.GetString("RotationDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save All 的本地化字符串。
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As... 的本地化字符串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale X 的本地化字符串。
        /// </summary>
        public static string ScaleX {
            get {
                return ResourceManager.GetString("ScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Y 的本地化字符串。
        /// </summary>
        public static string ScaleY {
            get {
                return ResourceManager.GetString("ScaleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary color 的本地化字符串。
        /// </summary>
        public static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected entities 的本地化字符串。
        /// </summary>
        public static string SelectedEntities {
            get {
                return ResourceManager.GetString("SelectedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected entity 的本地化字符串。
        /// </summary>
        public static string SelectedEntity {
            get {
                return ResourceManager.GetString("SelectedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crossing 的本地化字符串。
        /// </summary>
        public static string SelectionCrossing {
            get {
                return ResourceManager.GetString("SelectionCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Filter 的本地化字符串。
        /// </summary>
        public static string SelectionFilter {
            get {
                return ResourceManager.GetString("SelectionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        public static string SelectionWindow {
            get {
                return ResourceManager.GetString("SelectionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Origin 的本地化字符串。
        /// </summary>
        public static string SetOrigin {
            get {
                return ResourceManager.GetString("SetOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shape Font 的本地化字符串。
        /// </summary>
        public static string ShapeFont {
            get {
                return ResourceManager.GetString("ShapeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAD Text 的本地化字符串。
        /// </summary>
        public static string ShapeText {
            get {
                return ResourceManager.GetString("ShapeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show frames per second 的本地化字符串。
        /// </summary>
        public static string ShowFramesPerSecond {
            get {
                return ResourceManager.GetString("ShowFramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Image in New Window 的本地化字符串。
        /// </summary>
        public static string ShowImageInNewWindow {
            get {
                return ResourceManager.GetString("ShowImageInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Properties 的本地化字符串。
        /// </summary>
        public static string ShowProperties {
            get {
                return ResourceManager.GetString("ShowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplex 的本地化字符串。
        /// </summary>
        public static string Simplex {
            get {
                return ResourceManager.GetString("Simplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snap Marker 的本地化字符串。
        /// </summary>
        public static string SnapMarker {
            get {
                return ResourceManager.GetString("SnapMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snap marker color 的本地化字符串。
        /// </summary>
        public static string SnapMarkerColor {
            get {
                return ResourceManager.GetString("SnapMarkerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snap marker length 的本地化字符串。
        /// </summary>
        public static string SnapMarkerLength {
            get {
                return ResourceManager.GetString("SnapMarkerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snap marker line width 的本地化字符串。
        /// </summary>
        public static string SnapMarkerStrokeWidth {
            get {
                return ResourceManager.GetString("SnapMarkerStrokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snap marker type 的本地化字符串。
        /// </summary>
        public static string SnapMarkerType {
            get {
                return ResourceManager.GetString("SnapMarkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snap spacing X (0 = auto) 的本地化字符串。
        /// </summary>
        public static string SnapSpacingX {
            get {
                return ResourceManager.GetString("SnapSpacingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snap spacing Y (0 = auto) 的本地化字符串。
        /// </summary>
        public static string SnapSpacingY {
            get {
                return ResourceManager.GetString("SnapSpacingY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid 的本地化字符串。
        /// </summary>
        public static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spacing X 的本地化字符串。
        /// </summary>
        public static string SpacingX {
            get {
                return ResourceManager.GetString("SpacingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spacing Y 的本地化字符串。
        /// </summary>
        public static string SpacingY {
            get {
                return ResourceManager.GetString("SpacingY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spline 的本地化字符串。
        /// </summary>
        public static string Spline {
            get {
                return ResourceManager.GetString("Spline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spline drawing 的本地化字符串。
        /// </summary>
        public static string SplineDrawing {
            get {
                return ResourceManager.GetString("SplineDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Square 的本地化字符串。
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start cap 的本地化字符串。
        /// </summary>
        public static string StartCap {
            get {
                return ResourceManager.GetString("StartCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start X 的本地化字符串。
        /// </summary>
        public static string StartX {
            get {
                return ResourceManager.GetString("StartX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Y 的本地化字符串。
        /// </summary>
        public static string StartY {
            get {
                return ResourceManager.GetString("StartY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke 的本地化字符串。
        /// </summary>
        public static string Stroke {
            get {
                return ResourceManager.GetString("Stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke color 的本地化字符串。
        /// </summary>
        public static string StrokeColor {
            get {
                return ResourceManager.GetString("StrokeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke style 的本地化字符串。
        /// </summary>
        public static string StrokeStyle {
            get {
                return ResourceManager.GetString("StrokeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke width 的本地化字符串。
        /// </summary>
        public static string StrokeWidth {
            get {
                return ResourceManager.GetString("StrokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style 的本地化字符串。
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subdivisions 的本地化字符串。
        /// </summary>
        public static string Subdivision {
            get {
                return ResourceManager.GetString("Subdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap orientation 的本地化字符串。
        /// </summary>
        public static string SwapOrientation {
            get {
                return ResourceManager.GetString("SwapOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sweep 的本地化字符串。
        /// </summary>
        public static string Sweep {
            get {
                return ResourceManager.GetString("Sweep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target layer 的本地化字符串。
        /// </summary>
        public static string TargetLayer {
            get {
                return ResourceManager.GetString("TargetLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminal 的本地化字符串。
        /// </summary>
        public static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text AA 的本地化字符串。
        /// </summary>
        public static string TextAntialiasing {
            get {
                return ResourceManager.GetString("TextAntialiasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text drawing 的本地化字符串。
        /// </summary>
        public static string TextDrawing {
            get {
                return ResourceManager.GetString("TextDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle panel 的本地化字符串。
        /// </summary>
        public static string TogglePanel {
            get {
                return ResourceManager.GetString("TogglePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch between paper space and model editing through the viewport 的本地化字符串。
        /// </summary>
        public static string TogglePaperModelSpace {
            get {
                return ResourceManager.GetString("TogglePaperModelSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle primary side bar 的本地化字符串。
        /// </summary>
        public static string TogglePrimarySideBar {
            get {
                return ResourceManager.GetString("TogglePrimarySideBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle secondary side bar 的本地化字符串。
        /// </summary>
        public static string ToggleSecondarySideBar {
            get {
                return ResourceManager.GetString("ToggleSecondarySideBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Exception 的本地化字符串。
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled exception has occurred. The application will now exit. 的本地化字符串。
        /// </summary>
        public static string UnhandledExceptionExit {
            get {
                return ResourceManager.GetString("UnhandledExceptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicode 的本地化字符串。
        /// </summary>
        public static string Unicode {
            get {
                return ResourceManager.GetString("Unicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save changes to &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        public static string UnsavedDocumentMessageFormat {
            get {
                return ResourceManager.GetString("UnsavedDocumentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not saved yet 的本地化字符串。
        /// </summary>
        public static string UnsavedDocumentNoPath {
            get {
                return ResourceManager.GetString("UnsavedDocumentNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following documents have unsaved changes: 的本地化字符串。
        /// </summary>
        public static string UnsavedDocumentsMessage {
            get {
                return ResourceManager.GetString("UnsavedDocumentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsaved documents 的本地化字符串。
        /// </summary>
        public static string UnsavedDocumentsTitle {
            get {
                return ResourceManager.GetString("UnsavedDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsaved changes 的本地化字符串。
        /// </summary>
        public static string UnsavedDocumentTitle {
            get {
                return ResourceManager.GetString("UnsavedDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter valid finite values. Sizes and stroke widths must be greater than zero. 的本地化字符串。
        /// </summary>
        public static string UserSettingsInvalidValues {
            get {
                return ResourceManager.GetString("UserSettingsInvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertices 的本地化字符串。
        /// </summary>
        public static string Vertices {
            get {
                return ResourceManager.GetString("Vertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Viewport 的本地化字符串。
        /// </summary>
        public static string Viewport {
            get {
                return ResourceManager.GetString("Viewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Viewport scale 的本地化字符串。
        /// </summary>
        public static string ViewportScale {
            get {
                return ResourceManager.GetString("ViewportScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 的本地化字符串。
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
