namespace Direct2dCad.CommandLine;

public enum CadCommandLineDrawingMode
{
    Select,
    Line,
    CircleCenterRadius,
    CircleCenterDiameter,
    CircleTwoPoint,
    CircleThreePoint,
    EllipseCenter,
    EllipseAxisEnd,
    EllipseArc,
    ArcThreePoint,
    ArcStartCenterEnd,
    ArcStartCenterAngle,
    ArcStartCenterLength,
    ArcStartEndAngle,
    ArcStartEndDirection,
    ArcStartEndRadius,
    ArcCenterStartEnd,
    ArcCenterStartAngle,
    ArcCenterStartLength,
    ArcContinue,
    Rectangle,
    Polyline,
    Polygon,
    Spline,
    Text,
    SetOrigin,
    InsertBlock,
    LayoutViewport, Offset, Trim, Extend, Fillet, Chamfer, Join, Break, RectArray, PolarArray,
    DimLinearX, DimLinearY, DimAligned, DimRadius, DimDiameter, DimAngular, Leader,
    BooleanUnion, BooleanIntersection, BooleanDifference
}
