<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="11.0.0-preview.6.26359.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Direct2dCad.ChangeTracking\Direct2dCad.ChangeTracking.csproj" />
    <ProjectReference Include="..\Direct2dCad.Commands\Direct2dCad.Commands.csproj" />
    <ProjectReference Include="..\Direct2dCad.Db\Direct2dCad.Db.csproj" />
    <ProjectReference Include="..\Direct2dCad.HitTesting\Direct2dCad.HitTesting.csproj" />
    <ProjectReference Include="..\Direct2dCad.Indexing\Direct2dCad.Indexing.csproj" />
    <ProjectReference Include="..\Direct2dCad.Rendering\Direct2dCad.Rendering.csproj" />
  </ItemGroup>

</Project>
