using Direct2dCad.Db.Geometry;

namespace Direct2dCad.ViewModels.Tools;

internal sealed record CadEntityQueryOptions(
    string Scope,
    string? Type,
    string? Layer,
    bool SelectedOnly,
    string? Capability = null,
    IReadOnlyList<string>? Capabilities = null,
    IReadOnlyList<string>? Types = null,
    IReadOnlyList<string>? Layers = null,
    IReadOnlyList<long>? EntityIds = null,
    string? Owner = null,
    string? Name = null,
    string? NameContains = null,
    string? TextContains = null,
    string? SourceNameContains = null,
    bool? IsVisible = null,
    bool? IsLocked = null,
    bool? IsClosed = null,
    bool? HasFill = null,
    string? FillKind = null,
    string? ColorSource = null,
    string? LineWeightSource = null,
    string? GraphicStyle = null,
    string? FillStyle = null,
    string? DashStyle = null,
    int? MinZIndex = null,
    int? MaxZIndex = null,
    double? MinLength = null,
    double? MaxLength = null,
    double? MinWidth = null,
    double? MaxWidth = null,
    double? MinHeight = null,
    double? MaxHeight = null,
    double? MinRadius = null,
    double? MaxRadius = null,
    int? MinPointCount = null,
    int? MaxPointCount = null,
    double? MinOpacity = null,
    double? MaxOpacity = null,
    CadRectD? Bounds = null,
    string? SpatialRelation = null,
    string SortBy = "id",
    bool SortDescending = false,
    int Offset = 0,
    int Limit = 50);
