<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="Riok.Mapperly" Version="5.0.0-next.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Direct2dCad.Db\Direct2dCad.Db.csproj" />
  </ItemGroup>

</Project>
