<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vanara.PInvoke.Gdi32" Version="5.0.5" />
    <PackageReference Include="Vanara.PInvoke.Kernel32" Version="5.0.5" />
    <PackageReference Include="Vanara.PInvoke.Ole" Version="5.0.5" />
  </ItemGroup>

</Project>
