// Generated at development time. Static dispatch is NativeAOT safe.
using Avalonia.Controls;
namespace Direct2dCad.Avalonia;
internal static class GeneratedViews { public static Control? Create(object? model) => model switch {
        Direct2dCad.ViewModels.CadDocumentViewModel vm => new Views.Generated.CadAnnotationParametersView { DataContext = vm },
        Direct2dCad.ViewModels.MainViewModel vm => new Views.Generated.MainRibbonView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.AiAssistantSettingsDialogViewModel vm => new Views.Generated.AiAssistantSettingsDialog { DataContext = vm },
        Direct2dCad.ViewModels.Blocks.CreateBlockDialogViewModel vm => new Views.Generated.CreateBlockDialog { DataContext = vm },
        Direct2dCad.ViewModels.Settings.GridSpacingPresetEditorViewModel vm => new Views.Generated.GridSpacingPresetDialog { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.AiAssistantToolboxViewModel vm => new Views.Generated.AiAssistantToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.BlocksToolboxViewModel vm => new Views.Generated.BlocksToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.CommandLineToolboxViewModel vm => new Views.Generated.CommandLineToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.DocumentExplorerToolboxViewModel vm => new Views.Generated.DocumentExplorerToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntitySearchToolboxViewModel vm => new Views.Generated.EntitySearchToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.LayersToolboxViewModel vm => new Views.Generated.LayersToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.MessageToolboxViewModel vm => new Views.Generated.MessageToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.SelectionFilterToolboxViewModel vm => new Views.Generated.SelectionFilterToolboxView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.DocumentDisplaySettingsViewModel vm => new Views.Generated.DocumentDisplaySettingsView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.DocumentGridSettingsViewModel vm => new Views.Generated.DocumentGridSettingsView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.DocumentOriginSettingsViewModel vm => new Views.Generated.DocumentOriginSettingsView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.DocumentSettingsViewModel vm => new Views.Generated.DocumentSettingsDialog { DataContext = vm },
        Direct2dCad.ViewModels.Settings.UserSettings.GeneralUserSettingsViewModel vm => new Views.Generated.GeneralUserSettingsView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.UserSettings.InteractionUserSettingsViewModel vm => new Views.Generated.InteractionUserSettingsView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.UserSettings.RenderingUserSettingsViewModel vm => new Views.Generated.RenderingUserSettingsView { DataContext = vm },
        Direct2dCad.ViewModels.Settings.UserSettings.UserSettingsViewModel vm => new Views.Generated.UserSettingsDialog { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.ArcPropertyViewModel vm => new Views.Generated.ArcPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.BlockDefinitionPropertyViewModel vm => new Views.Generated.BlockDefinitionPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.BlockReferencePropertyViewModel vm => new Views.Generated.BlockReferencePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.CirclePropertyViewModel vm => new Views.Generated.CirclePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.CommonEntityPropertyViewModel vm => new Views.Generated.CommonEntityPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.EllipsePropertyViewModel vm => new Views.Generated.EllipsePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.ImagePropertyViewModel vm => new Views.Generated.ImagePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.LinePropertyViewModel vm => new Views.Generated.LinePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.MultiEntityPropertyViewModel vm => new Views.Generated.MultiEntityPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.PolylinePropertyViewModel vm => new Views.Generated.PolylinePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.RectanglePropertyViewModel vm => new Views.Generated.RectanglePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.SplinePropertyViewModel vm => new Views.Generated.SplinePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TextPropertyViewModel vm => new Views.Generated.TextPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientArcPropertyViewModel vm => new Views.Generated.TransientArcPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientBlockInsertionPropertyViewModel vm => new Views.Generated.TransientBlockInsertionPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientCirclePropertyViewModel vm => new Views.Generated.TransientCirclePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientEllipsePropertyViewModel vm => new Views.Generated.TransientEllipsePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientLinePropertyViewModel vm => new Views.Generated.TransientLinePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientPastePropertyViewModel vm => new Views.Generated.TransientPastePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientPolygonPropertyViewModel vm => new Views.Generated.TransientPolygonPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientPolylinePropertyViewModel vm => new Views.Generated.TransientPolylinePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientRectanglePropertyViewModel vm => new Views.Generated.TransientRectanglePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientSplinePropertyViewModel vm => new Views.Generated.TransientSplinePropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.TransientTextPropertyViewModel vm => new Views.Generated.TransientTextPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Toolboxes.EntityProperty.OleObjectPropertyViewModel vm => new Views.Generated.OleObjectPropertyView { DataContext = vm },
        Direct2dCad.ViewModels.Layouts.LayoutWorkspaceViewModel vm => new Views.Generated.LayoutOptionsView { DataContext = vm },
        _ => null
    }; }
