namespace Direct2dCad.Rendering;

public sealed record CadRenderStatistics(
    bool IsFullFrame,
    int DirtyRegionCount,
    int ScenePassCount,
    int VisibleEntityCount,
    int EntitySubmissionCount,
    int BlockReferenceCount,
    int ExpandedBlockEntityCount,
    int BlockDefinitionCommandListReplayCount,
    int BlockDefinitionCommandListBuildCount,
    int SelectionEntityCount,
    int SelectionCommandListReplayCount,
    int SelectionCommandListBuildCount,
    int CommandListReplayCount,
    int CommandListBuildCount,
    int TileReplayCount,
    int TileBuildCount,
    int FallbackEntityCount,
    int GeometryRealizationFillDrawCount,
    int GeometryRealizationStrokeDrawCount,
    int GeometryRealizationBuildCount,
    int GeometryRealizationFallbackCount,
    int GeometryRealizationCacheHitCount,
    int GeometryRealizationCacheMissCount,
    double GeometryRealizationBuildMilliseconds,
    long HatchLineSubmissionCount,
    int HatchSimplifiedLineFamilyCount,
    int OleTileBuildCount,
    long SceneTileCacheBytes,
    long CommandListCacheBytes,
    long SelectionCommandListCacheBytes,
    long BlockDefinitionCacheBytes,
    long GeometryRealizationCacheBytes,
    long HatchTileCacheBytes,
    long ImageBitmapCacheBytes,
    long OleTileCacheBytes,
    long GpuCacheBytes,
    long GpuCachePeakBytes,
    long GpuCacheBudgetBytes,
    int GpuCacheEvictionCount,
    int RenderCacheHitCount,
    int RenderCacheMissCount,
    int MicroEntityCandidateCount,
    int MicroEntityRepresentativeCount,
    int LargeSelectionFallbackCount,
    double DirtyPlanningMilliseconds,
    double VisibilityQueryMilliseconds,
    double CandidateSortingMilliseconds,
    double CpuEntitySubmissionMilliseconds,
    double CachePreparationMilliseconds,
    double BackgroundRenderMilliseconds,
    double EntityRenderMilliseconds,
    double TransientRenderMilliseconds,
    double SelectionRenderMilliseconds,
    double OlePreparationMilliseconds,
    double SurfaceDrawMilliseconds,
    double RenderDurationMilliseconds)
{
    public int BackgroundCommandListBuildCount { get; init; }
    public double BackgroundCommandListBuildMilliseconds { get; init; }
    public int MultiDeviceFrameCount { get; init; }
    public int MultiDeviceWorkerCount { get; init; }
    public int MultiDeviceEntityCount { get; init; }
    public double MultiDeviceRenderMilliseconds { get; init; }
    public long MultiDeviceGpuCacheBytes { get; init; }

    public double RenderCacheHitRatio =>
        RenderCacheHitCount + RenderCacheMissCount == 0
            ? 0
            : (double)RenderCacheHitCount /
              (RenderCacheHitCount + RenderCacheMissCount);

    public static CadRenderStatistics Empty { get; } = new(
        IsFullFrame: true,
        DirtyRegionCount: 0,
        ScenePassCount: 0,
        VisibleEntityCount: 0,
        EntitySubmissionCount: 0,
        BlockReferenceCount: 0,
        ExpandedBlockEntityCount: 0,
        BlockDefinitionCommandListReplayCount: 0,
        BlockDefinitionCommandListBuildCount: 0,
        SelectionEntityCount: 0,
        SelectionCommandListReplayCount: 0,
        SelectionCommandListBuildCount: 0,
        CommandListReplayCount: 0,
        CommandListBuildCount: 0,
        TileReplayCount: 0,
        TileBuildCount: 0,
        FallbackEntityCount: 0,
        GeometryRealizationFillDrawCount: 0,
        GeometryRealizationStrokeDrawCount: 0,
        GeometryRealizationBuildCount: 0,
        GeometryRealizationFallbackCount: 0,
        GeometryRealizationCacheHitCount: 0,
        GeometryRealizationCacheMissCount: 0,
        GeometryRealizationBuildMilliseconds: 0,
        HatchLineSubmissionCount: 0,
        HatchSimplifiedLineFamilyCount: 0,
        OleTileBuildCount: 0,
        SceneTileCacheBytes: 0,
        CommandListCacheBytes: 0,
        SelectionCommandListCacheBytes: 0,
        BlockDefinitionCacheBytes: 0,
        GeometryRealizationCacheBytes: 0,
        HatchTileCacheBytes: 0,
        ImageBitmapCacheBytes: 0,
        OleTileCacheBytes: 0,
        GpuCacheBytes: 0,
        GpuCachePeakBytes: 0,
        GpuCacheBudgetBytes: 0,
        GpuCacheEvictionCount: 0,
        RenderCacheHitCount: 0,
        RenderCacheMissCount: 0,
        MicroEntityCandidateCount: 0,
        MicroEntityRepresentativeCount: 0,
        LargeSelectionFallbackCount: 0,
        DirtyPlanningMilliseconds: 0,
        VisibilityQueryMilliseconds: 0,
        CandidateSortingMilliseconds: 0,
        CpuEntitySubmissionMilliseconds: 0,
        CachePreparationMilliseconds: 0,
        BackgroundRenderMilliseconds: 0,
        EntityRenderMilliseconds: 0,
        TransientRenderMilliseconds: 0,
        SelectionRenderMilliseconds: 0,
        OlePreparationMilliseconds: 0,
        SurfaceDrawMilliseconds: 0,
        RenderDurationMilliseconds: 0);
}
